project 'OOXX.xcodeproj'

# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'OOXX' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for OOXX
    inhibit_all_warnings!

 pod 'Fabric'
 pod 'Crashlytics'
 pod 'Firebase/Analytics'
 pod 'Firebase/Performance'
 pod 'Google-Mobile-Ads-SDK'

end
